### PR TITLE
Fix help message for EEPROM argparsers

### PR DESCRIPTION
**Pull request by Neon22**
help messaging for eeprom (which said calibration but meant eeprom).
Test simple branch process for workability

### CODE REVIEW

**Comment by Neon22** [comment]
super minor update to check workflow

**Comment by kzyapkov** [comment]
I see you want to do it "right", so let's do it right :) Please edit your commit message better reflect the change, a one-liner is acceptable here. Something like "Fix help message for EEPROM argparsers"

**Comment by Neon22** [comment]
I thought I was being helpful. but I'm seriously happy to do it anyway that works for you. Just let me know please.

**Comment by kzyapkov** [comment]
I meant the commit message, you can overwrite your commit object with `git commit --amend`, then `git push --force`

**Comment by kzyapkov** [comment]
Did some other work and integrated this fix, thanks!

**Pull request closed without merging**
